---
- name: Install requirements
  apt:
    name:
      - build-essential
      - libcairo2-dev
      - libjpeg-turbo8-dev
      - libpng-dev
      - libtool-bin
      - libossp-uuid-dev
      - libpango1.0-dev
      - libssh2-1-dev
      - libvncserver-dev
      - libssl-dev
      - libwebp-dev
      - freerdp2-dev

- name: Get server tarball
  get_url:
    url: "{{ guacd_mirror }}/guacamole/{{ guacd_version }}/source/guacamole-server-{{ guacd_version }}.tar.gz"
    dest: /tmp

- name: Extract server tarball
  unarchive:
    remote_src: yes
    src: /tmp/guacamole-server-{{ guacd_version }}.tar.gz
    dest: /tmp

- name: Configure server
  command: ./configure --with-init-dir=/etc/init.d
  args:
    chdir: /tmp/guacamole-server-{{ guacd_version }}

- name: Compile server
  make:
    chdir: /tmp/guacamole-server-{{ guacd_version }}

- name: Install server
  make:
    target: install
    chdir: /tmp/guacamole-server-{{ guacd_version }}

- name: Run ldconfig
  command: ldconfig

- name: Enable and start guacd
  systemd:
    name: guacd
    daemon_reload: yes
    enabled: yes
    state: started
