---
- name: Install requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-8-jdk-headless
    - tomcat8
    - maven

- name: Configure CORS
  template:
    src: web.xml.j2
    dest: "{{ hastexo_xblock_git_checkout }}/guacamole/src/main/webapp/WEB-INF/web.xml"
  when: NGINX_REDIRECT_TO_HTTPS and not devstack

- name: Build package
  command: mvn package
  args:
    chdir: "{{ hastexo_xblock_git_checkout }}/guacamole"

- name: Copy war file
  copy:
    remote_src: yes
    src: "{{ hastexo_xblock_git_checkout }}/guacamole/target/hastexo-xblock-{{ hastexo_xblock_version }}.war"
    dest: /var/lib/tomcat8/webapps/hastexo-xblock.war

- name: Remote checkout
  file:
    path: "{{ hastexo_xblock_git_checkout }}"
    state: absent

- name: Restart tomcat8
  systemd:
    name: tomcat8
    enabled: yes
    state: restarted

- name: Nginx include
  template:
    src=hastexo_xblock.j2
    dest="{{ COMMON_APP_DIR }}/nginx/include/lms/hastexo-xblock"
    owner=root
    group="{{ common_web_group }}"
  notify:
    - restart nginx
  when: not devstack

- name: "Supervisor scripts"
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ supervisor_available_dir }}/{{ item }}.conf"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
    mode: "0644"
  with_items:
    - suspender
    - reaper

- name: "Stop supervisor services"
  shell:  "{{ supervisor_ctl }} -c {{ supervisor_cfg }} stop {{ item }}:"
  with_items:
    - suspender
    - reaper
  when: disable_edx_services
  tags:
    - manage

- name: "Disable supervisor scripts"
  file:
    path: "{{ supervisor_cfg_dir }}/{{ item }}.conf"
    state: absent
  with_items:
    - suspender
    - reaper
  when: disable_edx_services
  tags:
    - manage

- name: "Enable supervisor scripts"
  file:
    src: "{{ supervisor_available_dir }}/{{ item }}.conf"
    dest: "{{ supervisor_cfg_dir }}/{{ item }}.conf"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
    mode: "0644"
    state: link
    force: yes
  with_items:
    - suspender
    - reaper
  when: not disable_edx_services
  tags:
    - manage

- name: Update supervisor configuration
  shell:  "{{ supervisor_ctl }} -c {{ supervisor_cfg }} update"
  register: supervisor_update
  changed_when: supervisor_update.stdout is defined and supervisor_update.stdout != ""
  tags:
    - manage

- name: Restart supervisor services
  shell:  "{{ supervisor_ctl }} -c {{ supervisor_cfg }} restart {{ item }}:"
  with_items:
    - suspender
    - reaper
  when: not disable_edx_services
  tags:
    - manage
